(global-set-key (kbd "s-D") 'dired)
(global-set-key (kbd "C-h C-f") 'find-function-at-point)
(global-set-key (kbd "C-h C-v") 'find-variable-at-point)
(global-set-key (kbd "C-x j") 'previous-buffer)
(global-set-key (kbd "C-x l") 'next-buffer)
(global-set-key "\C-cV" 'visit-tags-table)
(global-set-key (kbd "C-c d r") 'recentf-edit-list)
