(global-set-key (kbd "s-D") 'dired)
(global-set-key "\C-xd" 'insert-current-date)
(global-set-key (kbd "<f2>") 'open-my-init-file)
(global-set-key (kbd "C-h C-f") 'find-function-at-point)
(global-set-key (kbd "C-h C-v") 'find-variable-at-point)
(global-set-key "\C-cV" 'visit-tags-table)
(global-set-key (kbd "C-;") 'ace-window);
(global-set-key (kbd "<f7>") 'switch-to-minibuffer-window)
(global-set-key (kbd "s-r") 'sudo-find-file)
(global-set-key (kbd "C-c D") 'delete-file-and-buffer)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x C-b") 'helm-buffers-list)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-c m b") 'helm-bookmarks)
(global-set-key (kbd "C-c m r") 'helm-recentf)
(global-set-key (kbd "C-c d b") 'bookmark-delete)
(global-set-key (kbd "C-c d r") 'recentf-edit-list)
(global-set-key (kbd "M-i") 'helm-swoop)
(global-set-key (kbd "M-I") 'helm-swoop-back-to-last-point)
(global-set-key (kbd "C-c M-i") 'helm-multi-swoop)
(global-set-key (kbd "C-x M-i") 'helm-multi-swoop-all)
(global-set-key (kbd "C-c y p") 'youdao-dictionary-search-at-point+)
(global-set-key (kbd "C-c y b") 'youdao-dictionary-search-at-point)
(global-set-key (kbd "C-c y i") 'youdao-dictionary-search-from-input)
(global-set-key (kbd "C-c y v") 'youdao-dictionary-play-voice-at-point)
(global-set-key (kbd "C-x g") 'magit-status)
;; headline in file(show function lists(variables)?)
(global-set-key "\C-xp" 'helm-semantic-or-imenu)
