"---------------------------------------------------------------------------"
(use-package which-key
  :config ;; :config can be used to execute code after a package is loaded.
  (which-key-mode 1))
(use-package ace-window
  :init ;; :init keyword to execute code before a package is loaded.
  (setq aw-background nil))
(use-package evil)
(use-package powerline)
(use-package powerline-evil)
(use-package column-enforce-mode)
(use-package ace-jump-mode)
(use-package benchmark-init
  :config
  (add-hook 'after-init-hook 'benchmark-init/deactivate))
(use-package yasnippet
  :config
  (yas-global-mode t))
(use-package json-mode)
(use-package doom-themes)
(use-package helm-flyspell)
(use-package erlang)
(use-package helm-ag)
(use-package gorepl-mode)
(use-package gore-mode)
(use-package nodejs-repl)
(use-package go-autocomplete)
(use-package company-go)
(use-package company-lua)
(use-package helm-gtags)
(use-package company-php)
(use-package helm-projectile)
(use-package projectile)
(use-package magit)
(use-package org-bullets)
(use-package lua-mode)
(use-package shackle)
(use-package ggtags)
(use-package helm-swoop)
(use-package youdao-dictionary)
(use-package org-pomodoro)
(use-package helm)
(use-package jsx-mode)
(use-package ac-php)
(use-package php-mode)
(use-package flycheck-swift)
(use-package swift-mode)
(use-package elpy)
(use-package emmet-mode)
(use-package composer)
(use-package org)
(use-package ac-html)
(use-package js2-refactor)
(use-package python-environment)
(use-package concurrent)
(use-package sourcemap)
(use-package memoize)
(use-package mew)
(use-package skewer-mode)
(use-package xref-js2)
(use-package indium)
(use-package web-mode)
(use-package flycheck-irony)
(use-package company-irony-c-headers)
(use-package company-irony)
(use-package company-tern)
"---------------------------------------------------------------------------"
